import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  Highlight: {
    color: '#0066FF',
    textDecorationLine: 'underline',
  },
  basicContainerResto: {
    flex: 1,
    minHeight: 480,
  },
  basicContainer: {
    flex: 1,
    minHeight: 700,
  },
  paperinput: {
    width: 300,
    height: 20,
    backgroundColor: '#fff',
    paddingVertical: 10,
    borderColor: '#ccc',
    fontSize: 16,
    marginTop: 20,
  },
  input: {
    width: 300,
    height: 40,
    backgroundColor: '#f2f2f2',
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderColor: '#ccc',
    borderWidth: 1,
    borderRadius: 15,
    fontSize: 16,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 20,
  },
  segmentButton: {
    width: 300,
    height: 40,
    backgroundColor: '#f2f2f2',
    borderRadius: 15,
    fontSize: 16,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 20,
  },
  buttonDefault: {
    margin: 10,
  },
  surface: {
    padding: 8,
    margin: 10,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 4,
  },
  Image: {
    width: 200,
    height: 200,
  },
  contentBox: {
    height: '76%',
  },
  flexContainer: {
    flex: 1,
    backgroundColor: '#fff',
  },
  cover: {
    height: 119,
    width: 420,
  },
  row: {
    flexDirection: 'row',
  },
  homepagetext: {
    fontSize: 20,
    fontWeight: '900',
    marginTop: 24,
    marginLeft: 30,
    color: 'black',
  },
  text: {
    fontSize: 20,
    fontWeight: '900',
    marginTop: 24,
    marginLeft: 15,
    color: 'black',
  },
  textBasic: {
    color: 'black',
    fontSize: 16,
    fontWeight: 'bold',
  },
  buttonTitle: {
    fontWeight: 'bold',
    color: 'black',
    marginTop: 20,
    fontSize: 16,
  },
  buttonBox: {
    width: 108,
    height: 107,
    backgroundColor: '#A9FDAC',
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  flexButton: {
    justifyContent: 'space-around',
    flexDirection: 'row',
    marginTop: 80,
  },
  touchButton: {
    marginTop: 40,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  ImgPlacement: {
    width: 88,
    height: 88,
  },
  profileName: {
    fontFamily: 'Inter',
    fontWeight: 'bold',
    fontSize: 32,
    color: 'black',
    marginHorizontal: 20,
  },
  profileText: {
    fontFamily: 'Inter',
    fontSize: 15,
    color: 'black',
  },
  sticky: {
    position: 'absolute',
  },
  bottomSomething: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: 10,
    borderWidth: 1,
    borderColor: 'black',
    padding: 30,
  },
  Subheading: {
    fontWeight: 'bold',
    fontSize: 26,
    color: 'black',
    marginTop: 20,
  },
  button: {
    backgroundColor: '#A9FDAC',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    borderWidth: 1,
    marginVertical: 20,
    width: 300,
    height: 40,
  },
  logoutButton: {
    backgroundColor: '#d70000',
    alignItems: 'center',
    color: 'white',
    justifyContent: 'center',
    borderRadius: 8,
    marginTop: 10,
    width: 300,
    height: 40,
    marginBottom: 40,
    flexDirection: 'row',
  },
  centeredContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'column',
    backgroundColor: '#fff',
  },
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'column',
    backgroundColor: '#fff',
  },
  containerLogout: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'column',
    backgroundColor: '#fff',
    paddingTop: 20,
    marginTop: 20,
  },
  containerUncentered: {
    flex: 1,
    justifyContent: 'center',
    flexDirection: 'column',
    backgroundColor: '#fff',
    minHeight: '100%',
  },
  containerrow: {
    flex: 1,
    alignItems: 'center',
    flexDirection: 'row',
    paddingHorizontal: 40,
    justifyContent: 'space-evenly',
    backgroundColor: '#fff',
  },
  driverPic: {
    borderWidth: 2,
    borderColor: 'black',
    backgroundColor: 'gray',
    width: 125,
    height: 125,
    borderRadius: 8,
    marginTop: 10,
  },
  testing: {
    flex: 1,
  },
  profilePage: {
    height: '80%',
  },
  picture: {
    width: 200,
    height: 200,
    borderRadius: 100,
    backgroundColor: '#A9FDAC',
    justifyContent: 'center',
    alignItems: 'center',
  },
  banner: {
    backgroundColor: '#00BF63',
    height: 78,
    width: '100%',
  },
  box: {
    width: 300,
    height: 40,
    borderRadius: 10,
    backgroundColor: '#A9FDAC',
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: 10,
  },
  RestaurantBoxOutside: {
    width: 112,
    height: 106,
    borderWidth: 2,
    borderColor: 'black',
    backgroundColor: '#D9D9D9',
    borderRadius: 8,
    marginLeft: 10,
  },
  RestaurantBoxInside: {
    width: 108,
    height: 86,
    borderColor: 'black',
    backgroundColor: '#A9FDAC',
    borderRadius: 8,
    borderBottomWidth: 2,
  },
  textInput: {
    borderColor: 'gray',
    borderWidth: 1,
  },
  resultContainer: {
    flexDirection: 'row',
    padding: 10,
  },
  container2: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
  },
  checkboxWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 5,
  },
});

export {styles};
